/* Generated by re2c 0.13.6 on Sun Sep  8 17:58:13 2013 */
// Copyright (c) 2013 Plenluno All rights reserved.

#ifndef LIBNODE_DETAIL_HTTP_HEADER_SCANNER_H_
#define LIBNODE_DETAIL_HTTP_HEADER_SCANNER_H_

#include <libnode/http/header.h>

namespace libj {
namespace node {
namespace detail {
namespace http {

#define YYLIMIT     limit
#define YYCURSOR    cursor
#define YYMARKER    marker
#ifdef LIBJ_PF_WINDOWS
#define YYFILL(n)   NULL
#else
#define YYFILL(n)
#endif

template<typename YYCTYPE>
inline String::CPtr createLowerString(const YYCTYPE* buf, size_t len);

template<>
inline String::CPtr createLowerString(const char* buf, size_t len) {
    return String::create(buf, String::UTF8, len)->toLowerCase();
}

template<>
inline String::CPtr createLowerString(const char16_t* buf, size_t len) {
    return String::create(buf, String::UTF16, len)->toLowerCase();
}

template<>
inline String::CPtr createLowerString(const char32_t* buf, size_t len) {
    return String::create(buf, String::UTF32, len)->toLowerCase();
}

template<typename YYCTYPE>
inline String::CPtr scanHeaderField(const YYCTYPE* buf, size_t len) {
    if (!buf || !len) return String::create();

    const YYCTYPE* limit  = buf;
    const YYCTYPE* cursor = buf;
    const YYCTYPE* marker = NULL;


{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 32) YYFILL(32);
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy10;
	case 'C':
	case 'c':	goto yy2;
	case 'D':
	case 'd':	goto yy4;
	case 'E':
	case 'e':	goto yy11;
	case 'F':
	case 'f':	goto yy13;
	case 'H':
	case 'h':	goto yy14;
	case 'I':
	case 'i':	goto yy15;
	case 'L':
	case 'l':	goto yy12;
	case 'M':
	case 'm':	goto yy16;
	case 'O':
	case 'o':	goto yy19;
	case 'P':
	case 'p':	goto yy5;
	case 'R':
	case 'r':	goto yy17;
	case 'S':
	case 's':	goto yy18;
	case 'T':
	case 't':	goto yy6;
	case 'U':
	case 'u':	goto yy7;
	case 'V':
	case 'v':	goto yy8;
	case 'W':
	case 'w':	goto yy9;
	default:	goto yy20;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy552;
	case 'O':
	case 'o':	goto yy551;
	default:	goto yy3;
	}
yy3:
	{ return createLowerString(buf, len); }
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy531;
	case 'E':
	case 'e':	goto yy530;
	default:	goto yy3;
	}
yy5:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'R':
	case 'r':	goto yy497;
	default:	goto yy3;
	}
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy467;
	case 'I':
	case 'i':	goto yy466;
	case 'R':
	case 'r':	goto yy469;
	default:	goto yy3;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'P':
	case 'p':	goto yy450;
	case 'S':
	case 's':	goto yy449;
	default:	goto yy3;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy442;
	case 'I':
	case 'i':	goto yy443;
	default:	goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy420;
	case 'W':
	case 'w':	goto yy419;
	default:	goto yy3;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'C':
	case 'c':	goto yy260;
	case 'G':
	case 'g':	goto yy261;
	case 'L':
	case 'l':	goto yy263;
	case 'U':
	case 'u':	goto yy262;
	default:	goto yy3;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy245;
	case 'X':
	case 'x':	goto yy246;
	default:	goto yy3;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy214;
	case 'I':
	case 'i':	goto yy213;
	case 'O':
	case 'o':	goto yy212;
	default:	goto yy3;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'R':
	case 'r':	goto yy208;
	default:	goto yy3;
	}
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'O':
	case 'o':	goto yy204;
	default:	goto yy3;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy147;
	default:	goto yy3;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy135;
	default:	goto yy3;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy114;
	case 'E':
	case 'e':	goto yy113;
	default:	goto yy3;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy38;
	case 'T':
	case 't':	goto yy37;
	default:	goto yy3;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'R':
	case 'r':	goto yy23;
	case 'V':
	case 'v':	goto yy21;
	default:	goto yy3;
	}
yy20:
	yych = *++YYCURSOR;
	goto yy3;
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy29;
	default:	goto yy22;
	}
yy22:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy148;
	default:	goto yy384;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy24;
	default:	goto yy22;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy25;
	default:	goto yy22;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy26;
	default:	goto yy22;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy27;
	default:	goto yy22;
	}
yy27:
	++YYCURSOR;
	{ return node::http::LHEADER_ORIGIN; }
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy30;
	default:	goto yy22;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy31;
	default:	goto yy22;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy32;
	default:	goto yy22;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy33;
	default:	goto yy22;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy34;
	default:	goto yy22;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy35;
	default:	goto yy22;
	}
yy35:
	++YYCURSOR;
	{ return node::http::LHEADER_OVERWRITE; }
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy104;
	default:	goto yy22;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy41;
	case 'R':
	case 'r':	goto yy39;
	case 'T':
	case 't':	goto yy40;
	default:	goto yy22;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy100;
	default:	goto yy22;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy92;
	default:	goto yy22;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy42;
	default:	goto yy22;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy43;
	default:	goto yy22;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy44;
	default:	goto yy22;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy45;
	default:	goto yy22;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy46;
	default:	goto yy22;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy47;
	default:	goto yy22;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy48;
	default:	goto yy22;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy49;
	default:	goto yy22;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy50;
	default:	goto yy22;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy51;
	default:	goto yy22;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy52;
	default:	goto yy22;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy55;
	case 'E':
	case 'e':	goto yy54;
	case 'K':
	case 'k':	goto yy53;
	case 'P':
	case 'p':	goto yy56;
	case 'V':
	case 'v':	goto yy57;
	default:	goto yy22;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy89;
	default:	goto yy22;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy79;
	default:	goto yy22;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy73;
	default:	goto yy22;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy65;
	default:	goto yy22;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy58;
	default:	goto yy22;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy59;
	default:	goto yy22;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy60;
	default:	goto yy22;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy61;
	default:	goto yy22;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy62;
	default:	goto yy22;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy63;
	default:	goto yy22;
	}
yy63:
	++YYCURSOR;
	{ return node::http::LHEADER_SEC_WEBSOCKET_VERSION; }
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy66;
	default:	goto yy22;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy67;
	default:	goto yy22;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy68;
	default:	goto yy22;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy69;
	default:	goto yy22;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy70;
	default:	goto yy22;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy71;
	default:	goto yy22;
	}
yy71:
	++YYCURSOR;
	{ return node::http::LHEADER_SEC_WEBSOCKET_PROTOCOL; }
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy74;
	default:	goto yy22;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy75;
	default:	goto yy22;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy76;
	default:	goto yy22;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy77;
	default:	goto yy22;
	}
yy77:
	++YYCURSOR;
	{ return node::http::LHEADER_SEC_WEBSOCKET_ACCEPT; }
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy80;
	default:	goto yy22;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy81;
	default:	goto yy22;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy82;
	default:	goto yy22;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy83;
	default:	goto yy22;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy84;
	default:	goto yy22;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy85;
	default:	goto yy22;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy86;
	default:	goto yy22;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy87;
	default:	goto yy22;
	}
yy87:
	++YYCURSOR;
	{ return node::http::LHEADER_SEC_WEBSOCKET_EXTENSIONS; }
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy90;
	default:	goto yy22;
	}
yy90:
	++YYCURSOR;
	{ return node::http::LHEADER_SEC_WEBSOCKET_KEY; }
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy93;
	default:	goto yy22;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy94;
	default:	goto yy22;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy95;
	default:	goto yy22;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy96;
	default:	goto yy22;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy97;
	default:	goto yy22;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy98;
	default:	goto yy22;
	}
yy98:
	++YYCURSOR;
	{ return node::http::LHEADER_SET_COOKIE; }
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy101;
	default:	goto yy22;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy102;
	default:	goto yy22;
	}
yy102:
	++YYCURSOR;
	{ return node::http::LHEADER_SERVER; }
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy105;
	default:	goto yy22;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy106;
	default:	goto yy22;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy107;
	default:	goto yy22;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy108;
	default:	goto yy22;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy109;
	default:	goto yy22;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy110;
	default:	goto yy22;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy111;
	default:	goto yy22;
	}
yy111:
	++YYCURSOR;
	{ return node::http::LHEADER_STATUS_URI; }
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy119;
	case 'T':
	case 't':	goto yy120;
	default:	goto yy22;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy115;
	default:	goto yy22;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy116;
	default:	goto yy22;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy117;
	default:	goto yy22;
	}
yy117:
	++YYCURSOR;
	{ return node::http::LHEADER_RANGE; }
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy130;
	default:	goto yy22;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy121;
	default:	goto yy22;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy122;
	default:	goto yy22;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy123;
	default:	goto yy22;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy124;
	default:	goto yy22;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy125;
	default:	goto yy22;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy126;
	default:	goto yy22;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy127;
	default:	goto yy22;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy128;
	default:	goto yy22;
	}
yy128:
	++YYCURSOR;
	{ return node::http::LHEADER_RETRY_AFTER; }
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy131;
	default:	goto yy22;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy132;
	default:	goto yy22;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy133;
	default:	goto yy22;
	}
yy133:
	++YYCURSOR;
	{ return node::http::LHEADER_REFERER; }
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy136;
	default:	goto yy22;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy137;
	default:	goto yy22;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy138;
	default:	goto yy22;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy139;
	default:	goto yy22;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy140;
	default:	goto yy22;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy141;
	default:	goto yy22;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy142;
	default:	goto yy22;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy143;
	default:	goto yy22;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy144;
	default:	goto yy22;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy145;
	default:	goto yy22;
	}
yy145:
	++YYCURSOR;
	{ return node::http::LHEADER_MAX_FORWARDS; }
yy147:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy149;
	default:	goto yy148;
	}
yy148:
	{ return node::http::LHEADER_IF; }
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy153;
	case 'N':
	case 'n':	goto yy152;
	case 'R':
	case 'r':	goto yy151;
	case 'U':
	case 'u':	goto yy150;
	default:	goto yy22;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy188;
	default:	goto yy22;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy183;
	default:	goto yy22;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy173;
	default:	goto yy22;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy155;
	case 'O':
	case 'o':	goto yy154;
	default:	goto yy22;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy160;
	default:	goto yy22;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy156;
	default:	goto yy22;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy157;
	default:	goto yy22;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy158;
	default:	goto yy22;
	}
yy158:
	++YYCURSOR;
	{ return node::http::LHEADER_IF_MATCH; }
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy161;
	default:	goto yy22;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy162;
	default:	goto yy22;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy163;
	default:	goto yy22;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy164;
	default:	goto yy22;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy165;
	default:	goto yy22;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy166;
	default:	goto yy22;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy167;
	default:	goto yy22;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy168;
	default:	goto yy22;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy169;
	default:	goto yy22;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy170;
	default:	goto yy22;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy171;
	default:	goto yy22;
	}
yy171:
	++YYCURSOR;
	{ return node::http::LHEADER_IF_MODIFIED_SINCE; }
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy174;
	default:	goto yy22;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy175;
	default:	goto yy22;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy176;
	default:	goto yy22;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy177;
	default:	goto yy22;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy178;
	default:	goto yy22;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy179;
	default:	goto yy22;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy180;
	default:	goto yy22;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy181;
	default:	goto yy22;
	}
yy181:
	++YYCURSOR;
	{ return node::http::LHEADER_IF_NONE_MATCH; }
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy184;
	default:	goto yy22;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy185;
	default:	goto yy22;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy186;
	default:	goto yy22;
	}
yy186:
	++YYCURSOR;
	{ return node::http::LHEADER_IF_RANGE; }
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy189;
	default:	goto yy22;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy190;
	default:	goto yy22;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy191;
	default:	goto yy22;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy192;
	default:	goto yy22;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy193;
	default:	goto yy22;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy194;
	default:	goto yy22;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy195;
	default:	goto yy22;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy196;
	default:	goto yy22;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy197;
	default:	goto yy22;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy198;
	default:	goto yy22;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy199;
	default:	goto yy22;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy200;
	default:	goto yy22;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy201;
	default:	goto yy22;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy202;
	default:	goto yy22;
	}
yy202:
	++YYCURSOR;
	{ return node::http::LHEADER_IF_UNMODIFIED_SINCE; }
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy205;
	default:	goto yy22;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy206;
	default:	goto yy22;
	}
yy206:
	++YYCURSOR;
	{ return node::http::LHEADER_HOST; }
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy209;
	default:	goto yy22;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy210;
	default:	goto yy22;
	}
yy210:
	++YYCURSOR;
	{ return node::http::LHEADER_FROM; }
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy230;
	default:	goto yy22;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy227;
	default:	goto yy22;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy215;
	default:	goto yy22;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy216;
	default:	goto yy22;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy217;
	default:	goto yy22;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy218;
	default:	goto yy22;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy219;
	default:	goto yy22;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy220;
	default:	goto yy22;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy221;
	default:	goto yy22;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy222;
	default:	goto yy22;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy223;
	default:	goto yy22;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy224;
	default:	goto yy22;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy225;
	default:	goto yy22;
	}
yy225:
	++YYCURSOR;
	{ return node::http::LHEADER_LAST_MODIFIED; }
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy228;
	default:	goto yy22;
	}
yy228:
	++YYCURSOR;
	{ return node::http::LHEADER_LINK; }
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy232;
	case 'K':
	case 'k':	goto yy231;
	default:	goto yy22;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy238;
	default:	goto yy22;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy233;
	default:	goto yy22;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy234;
	default:	goto yy22;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy235;
	default:	goto yy22;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy236;
	default:	goto yy22;
	}
yy236:
	++YYCURSOR;
	{ return node::http::LHEADER_LOCATION; }
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy239;
	default:	goto yy22;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy240;
	default:	goto yy22;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy241;
	default:	goto yy22;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy242;
	default:	goto yy22;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy243;
	default:	goto yy22;
	}
yy243:
	++YYCURSOR;
	{ return node::http::LHEADER_LOCK_TOKEN; }
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy257;
	default:	goto yy22;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy247;
	default:	goto yy22;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy248;
	case 'I':
	case 'i':	goto yy249;
	default:	goto yy22;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy254;
	default:	goto yy22;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy250;
	default:	goto yy22;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy251;
	default:	goto yy22;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy252;
	default:	goto yy22;
	}
yy252:
	++YYCURSOR;
	{ return node::http::LHEADER_EXPIRES; }
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy255;
	default:	goto yy22;
	}
yy255:
	++YYCURSOR;
	{ return node::http::LHEADER_EXPECT; }
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy258;
	default:	goto yy22;
	}
yy258:
	++YYCURSOR;
	{ return node::http::LHEADER_ETAG; }
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy282;
	default:	goto yy22;
	}
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy280;
	default:	goto yy22;
	}
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy268;
	default:	goto yy22;
	}
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy264;
	default:	goto yy22;
	}
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy265;
	default:	goto yy22;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy266;
	default:	goto yy22;
	}
yy266:
	++YYCURSOR;
	{ return node::http::LHEADER_ALLOW; }
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy269;
	default:	goto yy22;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy270;
	default:	goto yy22;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy271;
	default:	goto yy22;
	}
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy272;
	default:	goto yy22;
	}
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Z':
	case 'z':	goto yy273;
	default:	goto yy22;
	}
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy274;
	default:	goto yy22;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy275;
	default:	goto yy22;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy276;
	default:	goto yy22;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy277;
	default:	goto yy22;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy278;
	default:	goto yy22;
	}
yy278:
	++YYCURSOR;
	{ return node::http::LHEADER_AUTHORIZATION; }
yy280:
	++YYCURSOR;
	{ return node::http::LHEADER_AGE; }
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy283;
	default:	goto yy22;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy284;
	case 'S':
	case 's':	goto yy285;
	default:	goto yy22;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy383;
	default:	goto yy22;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy286;
	default:	goto yy22;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy287;
	default:	goto yy22;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy288;
	default:	goto yy22;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy289;
	default:	goto yy22;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy290;
	default:	goto yy22;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy291;
	default:	goto yy22;
	}
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy292;
	default:	goto yy22;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy293;
	default:	goto yy22;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy294;
	default:	goto yy22;
	}
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy295;
	default:	goto yy22;
	}
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy296;
	case 'E':
	case 'e':	goto yy298;
	case 'M':
	case 'm':	goto yy297;
	case 'R':
	case 'r':	goto yy299;
	default:	goto yy22;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy343;
	default:	goto yy22;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy336;
	default:	goto yy22;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy322;
	default:	goto yy22;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy300;
	default:	goto yy22;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Q':
	case 'q':	goto yy301;
	default:	goto yy22;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy302;
	default:	goto yy22;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy303;
	default:	goto yy22;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy304;
	default:	goto yy22;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy305;
	default:	goto yy22;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy306;
	default:	goto yy22;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy307;
	case 'M':
	case 'm':	goto yy308;
	default:	goto yy22;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy315;
	default:	goto yy22;
	}
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy309;
	default:	goto yy22;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy310;
	default:	goto yy22;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy311;
	default:	goto yy22;
	}
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy312;
	default:	goto yy22;
	}
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy313;
	default:	goto yy22;
	}
yy313:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_REQUEST_METHOD; }
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy316;
	default:	goto yy22;
	}
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy317;
	default:	goto yy22;
	}
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy318;
	default:	goto yy22;
	}
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy319;
	default:	goto yy22;
	}
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy320;
	default:	goto yy22;
	}
yy320:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_REQUEST_HEADERS; }
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy323;
	default:	goto yy22;
	}
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy324;
	default:	goto yy22;
	}
yy324:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy325;
	default:	goto yy22;
	}
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy326;
	default:	goto yy22;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy327;
	default:	goto yy22;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy328;
	default:	goto yy22;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy329;
	default:	goto yy22;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy330;
	default:	goto yy22;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy331;
	default:	goto yy22;
	}
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy332;
	default:	goto yy22;
	}
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy333;
	default:	goto yy22;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy334;
	default:	goto yy22;
	}
yy334:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_EXPOSE_HEADERS; }
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy337;
	default:	goto yy22;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy338;
	default:	goto yy22;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy339;
	default:	goto yy22;
	}
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy340;
	default:	goto yy22;
	}
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy341;
	default:	goto yy22;
	}
yy341:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_MAX_AGE; }
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy344;
	default:	goto yy22;
	}
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy345;
	default:	goto yy22;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy346;
	default:	goto yy22;
	}
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy347;
	default:	goto yy22;
	}
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy350;
	case 'H':
	case 'h':	goto yy348;
	case 'M':
	case 'm':	goto yy349;
	case 'O':
	case 'o':	goto yy351;
	default:	goto yy22;
	}
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy376;
	default:	goto yy22;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy369;
	default:	goto yy22;
	}
yy350:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy358;
	default:	goto yy22;
	}
yy351:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy352;
	default:	goto yy22;
	}
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy353;
	default:	goto yy22;
	}
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy354;
	default:	goto yy22;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy355;
	default:	goto yy22;
	}
yy355:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy356;
	default:	goto yy22;
	}
yy356:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_ALLOW_ORIGIN; }
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy359;
	default:	goto yy22;
	}
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy360;
	default:	goto yy22;
	}
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy361;
	default:	goto yy22;
	}
yy361:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy362;
	default:	goto yy22;
	}
yy362:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy363;
	default:	goto yy22;
	}
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy364;
	default:	goto yy22;
	}
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy365;
	default:	goto yy22;
	}
yy365:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy366;
	default:	goto yy22;
	}
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy367;
	default:	goto yy22;
	}
yy367:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS; }
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy370;
	default:	goto yy22;
	}
yy370:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy371;
	default:	goto yy22;
	}
yy371:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy372;
	default:	goto yy22;
	}
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy373;
	default:	goto yy22;
	}
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy374;
	default:	goto yy22;
	}
yy374:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_ALLOW_METHODS; }
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy377;
	default:	goto yy22;
	}
yy377:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy378;
	default:	goto yy22;
	}
yy378:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy379;
	default:	goto yy22;
	}
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy380;
	default:	goto yy22;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy381;
	default:	goto yy22;
	}
yy381:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCESS_CONTROL_ALLOW_HEADERS; }
yy383:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy385;
	default:	goto yy384;
	}
yy384:
	{ return node::http::LHEADER_ACCEPT; }
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy389;
	case 'E':
	case 'e':	goto yy388;
	case 'L':
	case 'l':	goto yy387;
	case 'R':
	case 'r':	goto yy386;
	default:	goto yy22;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy413;
	default:	goto yy22;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy405;
	default:	goto yy22;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy397;
	default:	goto yy22;
	}
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy390;
	default:	goto yy22;
	}
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy391;
	default:	goto yy22;
	}
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy392;
	default:	goto yy22;
	}
yy392:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy393;
	default:	goto yy22;
	}
yy393:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy394;
	default:	goto yy22;
	}
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy395;
	default:	goto yy22;
	}
yy395:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCEPT_CHARSET; }
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy398;
	default:	goto yy22;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy399;
	default:	goto yy22;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy400;
	default:	goto yy22;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy401;
	default:	goto yy22;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy402;
	default:	goto yy22;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy403;
	default:	goto yy22;
	}
yy403:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCEPT_ENCODING; }
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy406;
	default:	goto yy22;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy407;
	default:	goto yy22;
	}
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy408;
	default:	goto yy22;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy409;
	default:	goto yy22;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy410;
	default:	goto yy22;
	}
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy411;
	default:	goto yy22;
	}
yy411:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCEPT_LANGUAGE; }
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy414;
	default:	goto yy22;
	}
yy414:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy415;
	default:	goto yy22;
	}
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy416;
	default:	goto yy22;
	}
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy417;
	default:	goto yy22;
	}
yy417:
	++YYCURSOR;
	{ return node::http::LHEADER_ACCEPT_RANGES; }
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy427;
	default:	goto yy22;
	}
yy420:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy421;
	default:	goto yy22;
	}
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy422;
	default:	goto yy22;
	}
yy422:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy423;
	default:	goto yy22;
	}
yy423:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy424;
	default:	goto yy22;
	}
yy424:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy425;
	default:	goto yy22;
	}
yy425:
	++YYCURSOR;
	{ return node::http::LHEADER_WARNING; }
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy428;
	default:	goto yy22;
	}
yy428:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy429;
	default:	goto yy22;
	}
yy429:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy430;
	default:	goto yy22;
	}
yy430:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy431;
	default:	goto yy22;
	}
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy432;
	default:	goto yy22;
	}
yy432:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy433;
	default:	goto yy22;
	}
yy433:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy434;
	default:	goto yy22;
	}
yy434:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy435;
	default:	goto yy22;
	}
yy435:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy436;
	default:	goto yy22;
	}
yy436:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy437;
	default:	goto yy22;
	}
yy437:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy438;
	default:	goto yy22;
	}
yy438:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy439;
	default:	goto yy22;
	}
yy439:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy440;
	default:	goto yy22;
	}
yy440:
	++YYCURSOR;
	{ return node::http::LHEADER_WWW_AUTHENTICATE; }
yy442:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy446;
	default:	goto yy22;
	}
yy443:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy444;
	default:	goto yy22;
	}
yy444:
	++YYCURSOR;
	{ return node::http::LHEADER_VIA; }
yy446:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy447;
	default:	goto yy22;
	}
yy447:
	++YYCURSOR;
	{ return node::http::LHEADER_VARY; }
yy449:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy457;
	default:	goto yy22;
	}
yy450:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy451;
	default:	goto yy22;
	}
yy451:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy452;
	default:	goto yy22;
	}
yy452:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy453;
	default:	goto yy22;
	}
yy453:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy454;
	default:	goto yy22;
	}
yy454:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy455;
	default:	goto yy22;
	}
yy455:
	++YYCURSOR;
	{ return node::http::LHEADER_UPGRADE; }
yy457:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy458;
	default:	goto yy22;
	}
yy458:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy459;
	default:	goto yy22;
	}
yy459:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy460;
	default:	goto yy22;
	}
yy460:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy461;
	default:	goto yy22;
	}
yy461:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy462;
	default:	goto yy22;
	}
yy462:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy463;
	default:	goto yy22;
	}
yy463:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy464;
	default:	goto yy22;
	}
yy464:
	++YYCURSOR;
	{ return node::http::LHEADER_USER_AGENT; }
yy466:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy491;
	default:	goto yy22;
	}
yy467:
	++YYCURSOR;
	{ return node::http::LHEADER_TE; }
yy469:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy470;
	default:	goto yy22;
	}
yy470:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy472;
	case 'N':
	case 'n':	goto yy471;
	default:	goto yy22;
	}
yy471:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy477;
	default:	goto yy22;
	}
yy472:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy473;
	default:	goto yy22;
	}
yy473:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy474;
	default:	goto yy22;
	}
yy474:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy475;
	default:	goto yy22;
	}
yy475:
	++YYCURSOR;
	{ return node::http::LHEADER_TRAILER; }
yy477:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy478;
	default:	goto yy22;
	}
yy478:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy479;
	default:	goto yy22;
	}
yy479:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy480;
	default:	goto yy22;
	}
yy480:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy481;
	default:	goto yy22;
	}
yy481:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy482;
	default:	goto yy22;
	}
yy482:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy483;
	default:	goto yy22;
	}
yy483:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy484;
	default:	goto yy22;
	}
yy484:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy485;
	default:	goto yy22;
	}
yy485:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy486;
	default:	goto yy22;
	}
yy486:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy487;
	default:	goto yy22;
	}
yy487:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy488;
	default:	goto yy22;
	}
yy488:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy489;
	default:	goto yy22;
	}
yy489:
	++YYCURSOR;
	{ return node::http::LHEADER_TRANSFER_ENCODING; }
yy491:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy492;
	default:	goto yy22;
	}
yy492:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy493;
	default:	goto yy22;
	}
yy493:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy494;
	default:	goto yy22;
	}
yy494:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy495;
	default:	goto yy22;
	}
yy495:
	++YYCURSOR;
	{ return node::http::LHEADER_TIMEOUT; }
yy497:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy498;
	case 'O':
	case 'o':	goto yy499;
	default:	goto yy22;
	}
yy498:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy526;
	default:	goto yy22;
	}
yy499:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy500;
	default:	goto yy22;
	}
yy500:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy501;
	default:	goto yy22;
	}
yy501:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy502;
	default:	goto yy22;
	}
yy502:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy503;
	default:	goto yy22;
	}
yy503:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy504;
	default:	goto yy22;
	}
yy504:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy505;
	default:	goto yy22;
	}
yy505:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy506;
	default:	goto yy22;
	}
yy506:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy508;
	case 'O':
	case 'o':	goto yy507;
	default:	goto yy22;
	}
yy507:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy517;
	default:	goto yy22;
	}
yy508:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy509;
	default:	goto yy22;
	}
yy509:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy510;
	default:	goto yy22;
	}
yy510:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy511;
	default:	goto yy22;
	}
yy511:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy512;
	default:	goto yy22;
	}
yy512:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy513;
	default:	goto yy22;
	}
yy513:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy514;
	default:	goto yy22;
	}
yy514:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy515;
	default:	goto yy22;
	}
yy515:
	++YYCURSOR;
	{ return node::http::LHEADER_PROXY_AUTHENTICATE; }
yy517:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy518;
	default:	goto yy22;
	}
yy518:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Z':
	case 'z':	goto yy519;
	default:	goto yy22;
	}
yy519:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy520;
	default:	goto yy22;
	}
yy520:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy521;
	default:	goto yy22;
	}
yy521:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy522;
	default:	goto yy22;
	}
yy522:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy523;
	default:	goto yy22;
	}
yy523:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy524;
	default:	goto yy22;
	}
yy524:
	++YYCURSOR;
	{ return node::http::LHEADER_PROXY_AUTHORIZATION; }
yy526:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy527;
	default:	goto yy22;
	}
yy527:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy528;
	default:	goto yy22;
	}
yy528:
	++YYCURSOR;
	{ return node::http::LHEADER_PRAGMA; }
yy530:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy537;
	case 'S':
	case 's':	goto yy538;
	default:	goto yy22;
	}
yy531:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy532;
	case 'V':
	case 'v':	goto yy533;
	default:	goto yy22;
	}
yy532:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy535;
	default:	goto yy22;
	}
yy533:
	++YYCURSOR;
	{ return node::http::LHEADER_DAV; }
yy535:
	++YYCURSOR;
	{ return node::http::LHEADER_DATE; }
yy537:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy548;
	default:	goto yy22;
	}
yy538:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy539;
	default:	goto yy22;
	}
yy539:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy540;
	default:	goto yy22;
	}
yy540:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy541;
	default:	goto yy22;
	}
yy541:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy542;
	default:	goto yy22;
	}
yy542:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy543;
	default:	goto yy22;
	}
yy543:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy544;
	default:	goto yy22;
	}
yy544:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy545;
	default:	goto yy22;
	}
yy545:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy546;
	default:	goto yy22;
	}
yy546:
	++YYCURSOR;
	{ return node::http::LHEADER_DESTINATION; }
yy548:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy549;
	default:	goto yy22;
	}
yy549:
	++YYCURSOR;
	{ return node::http::LHEADER_DEPTH; }
yy551:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy565;
	case 'O':
	case 'o':	goto yy566;
	default:	goto yy22;
	}
yy552:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy553;
	default:	goto yy22;
	}
yy553:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy554;
	default:	goto yy22;
	}
yy554:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy555;
	default:	goto yy22;
	}
yy555:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy556;
	default:	goto yy22;
	}
yy556:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy557;
	default:	goto yy22;
	}
yy557:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy558;
	default:	goto yy22;
	}
yy558:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy559;
	default:	goto yy22;
	}
yy559:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy560;
	default:	goto yy22;
	}
yy560:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy561;
	default:	goto yy22;
	}
yy561:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy562;
	default:	goto yy22;
	}
yy562:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy563;
	default:	goto yy22;
	}
yy563:
	++YYCURSOR;
	{ return node::http::LHEADER_CACHE_CONTROL; }
yy565:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy572;
	case 'T':
	case 't':	goto yy571;
	default:	goto yy22;
	}
yy566:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy567;
	default:	goto yy22;
	}
yy567:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy568;
	default:	goto yy22;
	}
yy568:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy569;
	default:	goto yy22;
	}
yy569:
	++YYCURSOR;
	{ return node::http::LHEADER_COOKIE; }
yy571:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy580;
	default:	goto yy22;
	}
yy572:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy573;
	default:	goto yy22;
	}
yy573:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy574;
	default:	goto yy22;
	}
yy574:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy575;
	default:	goto yy22;
	}
yy575:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy576;
	default:	goto yy22;
	}
yy576:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy577;
	default:	goto yy22;
	}
yy577:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy578;
	default:	goto yy22;
	}
yy578:
	++YYCURSOR;
	{ return node::http::LHEADER_CONNECTION; }
yy580:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy581;
	default:	goto yy22;
	}
yy581:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy582;
	default:	goto yy22;
	}
yy582:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy583;
	default:	goto yy22;
	}
yy583:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy584;
	case 'L':
	case 'l':	goto yy585;
	case 'M':
	case 'm':	goto yy586;
	case 'R':
	case 'r':	goto yy587;
	case 'T':
	case 't':	goto yy588;
	default:	goto yy22;
	}
yy584:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy623;
	default:	goto yy22;
	}
yy585:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy603;
	case 'E':
	case 'e':	goto yy602;
	case 'O':
	case 'o':	goto yy601;
	default:	goto yy22;
	}
yy586:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy598;
	default:	goto yy22;
	}
yy587:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy593;
	default:	goto yy22;
	}
yy588:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy589;
	default:	goto yy22;
	}
yy589:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy590;
	default:	goto yy22;
	}
yy590:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy591;
	default:	goto yy22;
	}
yy591:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_TYPE; }
yy593:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy594;
	default:	goto yy22;
	}
yy594:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy595;
	default:	goto yy22;
	}
yy595:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy596;
	default:	goto yy22;
	}
yy596:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_RANGE; }
yy598:
	yych = *++YYCURSOR;
	switch (yych) {
	case '5':	goto yy599;
	default:	goto yy22;
	}
yy599:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_MD5; }
yy601:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy616;
	default:	goto yy22;
	}
yy602:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy611;
	default:	goto yy22;
	}
yy603:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy604;
	default:	goto yy22;
	}
yy604:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy605;
	default:	goto yy22;
	}
yy605:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy606;
	default:	goto yy22;
	}
yy606:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy607;
	default:	goto yy22;
	}
yy607:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy608;
	default:	goto yy22;
	}
yy608:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy609;
	default:	goto yy22;
	}
yy609:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_LANGUAGE; }
yy611:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy612;
	default:	goto yy22;
	}
yy612:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy613;
	default:	goto yy22;
	}
yy613:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy614;
	default:	goto yy22;
	}
yy614:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_LENGTH; }
yy616:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy617;
	default:	goto yy22;
	}
yy617:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy618;
	default:	goto yy22;
	}
yy618:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy619;
	default:	goto yy22;
	}
yy619:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy620;
	default:	goto yy22;
	}
yy620:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy621;
	default:	goto yy22;
	}
yy621:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_LOCATION; }
yy623:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy624;
	default:	goto yy22;
	}
yy624:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy625;
	default:	goto yy22;
	}
yy625:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy626;
	default:	goto yy22;
	}
yy626:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy627;
	default:	goto yy22;
	}
yy627:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy628;
	default:	goto yy22;
	}
yy628:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy629;
	default:	goto yy22;
	}
yy629:
	++YYCURSOR;
	{ return node::http::LHEADER_CONTENT_ENCODING; }
}

}

}  // namespace http
}  // namespace detail
}  // namespace node
}  // namespace libj

#endif  // LIBNODE_DETAIL_HTTP_HEADER_SCANNER_H_
